---  
  - name: Include vars
    include_vars: variables.yml

  - name: update apt-get
    become: yes
    shell: 'apt-get update'

  - name: Cloning checkbox
    git:
        repo: "https://github.com/rshu/checkbox.io.git"
        dest: "{{home_path}}/checkbox"

  - name: Install Python PIP RPMs
    become: true
    package:
      name: python3-pip
      state: present

  - name: Install Several Packages
    become: yes
    apt:
      name: ['wget','mongodb','nginx']

  - name: Update nodejs
    become: yes
    shell: 'curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -'
    
  - name: Update nodejs
    become: yes
    shell: 'sudo apt-get install -y nodejs' 

  - name: Allow port 8080
    become: yes
    ufw:
      rule: allow
      port: 8080

  - name: Allow port 80
    become: yes
    ufw:
      rule: allow
      port: 80

  - name: Allow open ssh
    become: yes
    ufw:
      rule: allow
      name: OpenSSH

  - name: Allow everything and enable UFW
    become: yes
    ufw:
      state: enabled

  - name: Allow 'Nginx HTTP'
    become: yes
    ufw:
      rule: allow
      name: 'Nginx HTTP'

  - name: Allow port 3002
    become: yes
    ufw:
      rule: allow
      port: 3002

  - name: Allow port 27017
    become: yes
    ufw:
      rule: allow
      port: 27017

  - name: Install the latest pymongo package
    pip: name=pymongo state=latest use_mirrors=no

  - name: Create MongoDB root user siteRootAdmin
    mongodb_user:
      login_port: 27017
      database: admin
      name: '{{mongo_admin_user}}'
      password: '{{mongo_admin_password}}'
      roles: root

  - name: Create MongoDB administrative user siteUserAdmin
    mongodb_user:
      login_user: '{{mongo_admin_user}}'
      login_password: '{{mongo_admin_password}}'
      login_port: 27017
      database: admin
      name: '{{mongo_admin_user}}'
      password: '{{mongo_admin_password}}'
      roles:
        - { db: "admin", role: "userAdminAnyDatabase" }

  - name: Install python-mysql
    apt: pkg=python3-pymysql state=present update_cache=yes
    become: yes
  

  - name: Install chai
    become: yes
    npm:
      name: 'chai'
      path: /app/location

  - name: Install fs
    become: yes
    npm:
      name: 'fs'
      path: /app/location

  - name: Install assert
    become: yes
    npm:
      name: 'assert'
      path: /app/location

  - name: Install got
    become: yes
    npm:
      name: 'got'
      path: /app/location

  - name: Install mocha
    become: yes
    npm:
      name: 'mocha'
      path: /app/location


  - name: Install request
    become: yes
    npm:
      name: 'request'
      path: /app/location
      
  - name: Install pm2
    become: yes
    npm:
      name: 'pm2'
      path: /app/location

  - name: change bashrc
    blockinfile:
      path: '~/.bashrc'
      block: |
            export MONGO_PORT=27017
            export MONGO_IP=127.0.0.1
            export MONGO_USER={{mongo_admin_user}}
            export MONGO_PASSWORD={{mongo_admin_password}}
            export MAIL_USER='{{email_username}}'
            export MAIL_PASSWORD='{{email_password}}'
            export MAIL_SMTP=smtp.gmail.com
            export APP_PORT=3002
      insertbefore: EOF

  - name: Copy default to /etc/nginx/sites-available/default
    become: yes
    template: src=templates/default dest=/etc/nginx/sites-available/default

  - name: Copy nginx.conf to /etc/nginx/nginx.conf
    become: yes
    template: src=templates/nginx.conf dest=/etc/nginx/nginx.conf

  - name: npm install
    become: yes
    command: chdir={{home_path}}/checkbox/server-side/site npm install

  - name: npm install 
    become: yes
    command: chdir={{home_path}}/checkbox/server-side/site npm install -g pm2

  - name: restart nginx
    become: yes
    service:
      name: nginx
      state: restarted

  - name: start server.js 
    become: yes
    command: chdir={{home_path}}/checkbox/server-side/site node server.js

